sudo: false
language: node_js
node_js:
  - '5'

env:
  global:
    - CXX=g++-4.8
    - REPO_SLUG=ethcore/eth-node-status-page
    # SAUCE_USERNAME
    - secure: ekgApR8RUUyQVlG4U6HA85AuFZFcM697MdVeNFeceIY9hozSB0pI/GMRysThN58sNP2m8j0HPz9tEUiOJrW2gyj8t56ZZ9jJrru0dPbNIyQsQLafRslV372+tQxk0B/hC1LvvGcYNoveAgCaRzKYJSDs41a5YXrknH0i0s5Z7M1yU7KHT1JV6JfymeY8QjITQqmjXVjbUDZLc+BTww08sg+EM1EpJJCRNAk7TBouI6odLRyg0mZf6O/Zd7M/a95trzlk32ULgegdDXlohQrqXEBIHcw71OauI7ZvCaIRE+DDVQ2tvnISit9fxmqyLelOB0viLDW6JIPeglFntepivpLWzBI42TNTdpKm8t0wGHJ54pMyzSziKH4JSwKcUpLLlQp0bxfo+JZBfEgzxfjfp1wpJCMZBKMj5YrBmlVxrizGwe4WuT7ZqQ6IeOV1t/F2twNGLdUgTCYHyeBejgQOMsEFtVCHIC71zZ4EzSmGeolPIhf6csegy4gphaMh1Ymwh+x9QYoq3grNAf7t3575frFO3t2y3CRbwh0+3JQkvQuJ9FuJoRAX5zlplvot3Xx8P1Y5LPZsejL2bxvPCvk76aVINQV5HeL1qZdZV06mgJtI+pYthWFSKse2Ho+NtZcrI082OdOIDtNYBbCEG4Gw+WwU8R53tEufNaEO2rMoPls=
    # SAUCE_ACCESS_KEY
    - secure: aXMVEMSDJkImOoNQdK4bialK9/wj8X56rs4wyOwYyN5ZJHEKNqdopyfFXU65IENGbFHnpDVU1MMj9E2cU8QtjKm5F19w1pjPSV4kNEXZIVbnF4x9kDS7Sob9IMFLA3KZbsiOdnHzs6EuVk6KlPbqUMzd+g23+unPsaenFUGVLV1GgaAPLCOvCkxVUsMnixR3RQU1InI46EK7GcHFwXusiiDAaL55Ymj26LqwaY5fiM1TunNFEBH2klq6mTl3wnMBRioexwsfhGplOszBH7AwFywNARz2jJIbYLmbihXi3CifZk+rslWPPI04uIRgtdwsbKDed/t0sK3YPT+Z1N3NUK4LGyeGes5TejbKg0l+/ygxJLFMvaQLGy04zDfLVK8f+e7jOzIg3fqtsOmD9dSW4SkKF24EuYCdO3H1elOU4atwk1/3JRtxXjxcDWzFkrUetOdoEJhtjUWJhfNxmlybxRiQyHetfXegkgu7jU9GNiHegdFK2oMxNwGOv/2gUcMrUheQ/Zue0rZaEZLA2mNteXaE+A8KkB0/RYefyWcfLTaA/WpXpc3lncGwKX2Z4r4IhjG+qlB1WN5xkRa9/xH54U1+JjgF/omC1PS7YlLWywNt/IAmUrbDgn/Z0KKtS+WYQdrDrMlwTKp1/rkVKZ+FhFNuQj2HJVURK9G0f8GWS7o=
    # GITHUB_TOKEN with public repo access
    - secure: dZW1Auq9n4L4pw/BJO1/IU1MO9CCMk3xzm/UIqatVX+R6W51lHBysxGW7vfHntyBbaOJxcX/RA/SE6+JeSujqkXad137bJBhwsWv4GrjeCrSwF/1hd0/uk0KtFJ5uEmOWckBRE9qw5VeRm7RrwH4tw/q+juJjZTjWLXQIYm3QXDtDFDQQ0/Pe1YaCya/CeTOOfJ+Sk/cSdFmNPqTP+RXt3oi8bUlrkXk5/oIbl+rrMZWHVv75zEQZQbdRg3YniCunGQk0gpshpkvcf0N6A9s7f7wz12wCQoErOSap6kvoUyVNO+27OrSOsLAZAe9z8IXNvthnef8/6kEdyzMUQAMg32tkw0Dtuo3ZLcYouLKQsiwO7zRgOGIaZreEfcA90XV3Sv7PKxURJRR/pfqDHNwpi3OmlcJVASWc+FrH1rauo2E31OVvP2XSeRhT2yxUXpfhBB983W9JF6WsAFUKhwVYg+be7yaokfBUEb7uJd1BafLsIOa+qm/NpxhgkzHM/cB+z8CbUEDdSz6+ZxEv0QT2jt7QnLgD6L1aRRfV8B74DA5D2SP6dE2YMWkxCDMTUZkhDcaijNdN5HoilW3sdW4Zk9MSGzlU7j5amvQ+B3YFcFwFiNHq0ZlwJ/Yi6/ijSZCXN0u0N/GFpBiht1ixL3mhQmVRgOrrQlKXs0QK2nkdoI=

matrix:
  include:
  - env: SCRIPT=lint
  - env: SCRIPT=testOnce
  - env: SCRIPT=nightwatchCI
    addons:
      sauce_connect: true

cache:
  directories:
    - node_modules

before_script:
  - if [ "$SCRIPT" == "nightwatchCI" ]; then npm run startTest & fi
  - if [ "$SCRIPT" == "nightwatchCI" ]; then sleep 25; fi

script: npm run $SCRIPT

after_success:
  - ./scripts/deploy-to-gh-pages.sh
