sudo: false
language: node_js
node_js:
  - '5'

matrix:
  env:
    - PROJECT=status
    - PROJECT=home
    - SCRIPT=lint
    - SCRIPT=testOnce
    - SCRIPT=coveralls

cache:
  directories:
    - node_modules

script:
  - cd $PROJECT
  - if [ "$SCRIPT" ]; then npm run $SCRIPT; fi
  # - if [ "$E2E" ] && [ "$SAUCE_ACCESS_KEY" ]; then npm run startTest & sleep 25 && npm run $E2E; fi

after_success:
  # - ./scripts/deploy-to-gh-pages.sh
