sudo: false
language: node_js
node_js:
  - '5'

matrix:
  include:
  - env: SCRIPT=lint
  - env: SCRIPT=testOnce
  - env: SCRIPT=nightwatchCI
    addons:
      sauce_connect:
        username: "ethcoreHQ"
        access_key:
          secure: "j5YiOnXEBSdSHGtEgmU6IwoEEvdTr7NjqEsGRGzaef3EMpXusc5D+J/NepOtG1JyrENnXxvy1LO4gvZesm2DUBUT8eaTxryDQKof5wM7d7w3vDwvM/spWf4JOcFn6g0357Ns21tuqgHgh79tEpwjBXspo5Ta3OSTc3Fihl5c0nOHJpnfYERRKr/RNWUqFHuUiBzc0W/7tf9aPtAkJAmS45IuPt+Q9HDWKU0Q7LZkpqRD2uWrlfBonjfl259rkanmv6oxJITkn7wEWpULr2gscpTSHvfJYqDxmR50Aa/TqtPSslksCu1StArYjZF5ENZs59uSjELWd3PWIAF0Xzig3FlsL4dq9Ea32wKHuw4KhEKmjOO7yGggOOJklzYa8ckhBIUgwtvE70QUGu0P4FbO5u1hcxF7s77sSmT0naFcdEXJ0e8uyMb7RZqc2utC78tCUvo1CgZjeShdr8X35nXLmnFBfwdBwfWt6GX6hKRee7iR+sDsOSZvwxin1O4UxEf6Iz5CiFdDoOk07mODDcAKQv1JtALPQXM2Tof3xy6VRS+G/hQMEnDVAt9OyQwIoZRap5xWDW5xtnJYbWNU7ekF1cpfHJS7qXSjHgorIE8ed2jwp9q9iXwqsdluj9KPdgMokhmj14Ngfxhv0xdQahQTnXNfZB6/rjXmoNP6cewMkys="

cache:
  directories:
    - node_modules

env:
  global:
    - CXX=g++-4.8

before_script:
  - if [ "$SCRIPT" == "nightwatchCI" ]; then npm run startTest & fi
  - if [ "$SCRIPT" == "nightwatchCI" ]; then sleep 15; fi

script: npm run $SCRIPT