language: rust

rust:
  - stable
  - beta
  - nightly
env:
  - PROJECT=home
  - PROJECT=wallet
  - PROJECT=status

cache:
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/home/target
    - $TRAVIS_BUILD_DIR/wallet/target
    - $TRAVIS_BUILD_DIR/status/target

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

script:
  - cd $PROJECT
  - cargo build
  - cargo test --release

