sudo: false
language: node_js
node_js:
  - '5'

env:
  global:
    - CXX=g++-4.8
    - REPO_SLUG=ethcore/eth-node-status-page
    # SAUCE_ACCESS_KEY
    - secure: N+6v6zQLaLukclH4IrNESyHl6B5E98hY/DHhGNf255ChR4N+T/rCRNlgXU4CFS9xHoQNMlOaMU0nFJrVK1aYMpuzXtCtTY6LwmANVPE7XmpyVQfID2D2fbjWOnsDGAFnc7pmFkSkG6HONGYQit/cgUCG8Nsi1tnJHev9WRVaHZmpvwWh3ILf7iUyUtee4ZkWnEpdOCI/H+JFxAPffUK0beiMjUkdnhOrPcDZg8aYOqkF023sbhWRYkmJfUug4qjo1WgxF85B3/VhcRWouZ/dzzQyuv/Iua7E3lGTNiQi+cOA+g081cyZi+j4X9WOSBIZbYOycZ79W/NKWWKx4XTTAKkbUNIEjWC3wvwj7Qagk++fSS6mysYM15MaKoGhh6BbGV/640JZiO9loPWa1ezIhlMQqbRiS56HmJfled0RCZ5gXDQ1QLj+o0ION2XNVC+KOx1OmMi19Cx7GAL1KiAq0PWGjzD/+QP4AbPvAGp47y2tiAlrsnQ7Cwg4jlSt9Oycd7qgUa3P3pzUgqd0lQR5KeBSR/GXyRs6Ig4p8hBE/JgO3RAxuqEaSqMURsW7QedO2pHdJxAiVeqU54bdSRQ/X0gMbT0Ce3XfHkHRyYVN+ZE5p+ckrjEw1OGQIiN4wj8uXP/R1+IvuN+8UoIEC4vmkheXu+hWDxwt4YJxjnLm/+A=
    # GITHUB_TOKEN with public repo access
    - secure: dZW1Auq9n4L4pw/BJO1/IU1MO9CCMk3xzm/UIqatVX+R6W51lHBysxGW7vfHntyBbaOJxcX/RA/SE6+JeSujqkXad137bJBhwsWv4GrjeCrSwF/1hd0/uk0KtFJ5uEmOWckBRE9qw5VeRm7RrwH4tw/q+juJjZTjWLXQIYm3QXDtDFDQQ0/Pe1YaCya/CeTOOfJ+Sk/cSdFmNPqTP+RXt3oi8bUlrkXk5/oIbl+rrMZWHVv75zEQZQbdRg3YniCunGQk0gpshpkvcf0N6A9s7f7wz12wCQoErOSap6kvoUyVNO+27OrSOsLAZAe9z8IXNvthnef8/6kEdyzMUQAMg32tkw0Dtuo3ZLcYouLKQsiwO7zRgOGIaZreEfcA90XV3Sv7PKxURJRR/pfqDHNwpi3OmlcJVASWc+FrH1rauo2E31OVvP2XSeRhT2yxUXpfhBB983W9JF6WsAFUKhwVYg+be7yaokfBUEb7uJd1BafLsIOa+qm/NpxhgkzHM/cB+z8CbUEDdSz6+ZxEv0QT2jt7QnLgD6L1aRRfV8B74DA5D2SP6dE2YMWkxCDMTUZkhDcaijNdN5HoilW3sdW4Zk9MSGzlU7j5amvQ+B3YFcFwFiNHq0ZlwJ/Yi6/ijSZCXN0u0N/GFpBiht1ixL3mhQmVRgOrrQlKXs0QK2nkdoI=

matrix:
  include:
  - env: SCRIPT=lint
  - env: SCRIPT=testOnce
  - env: SCRIPT=nightwatchCI
    addons:
      sauce_connect: true

cache:
  directories:
    - node_modules

before_script:
  - if [ "$SCRIPT" == "nightwatchCI" ]; then npm run startTest & fi
  - if [ "$SCRIPT" == "nightwatchCI" ]; then sleep 25; fi

script: npm run $SCRIPT

after_success:
  - ./scripts/deploy-to-gh-pages.sh
