sudo: false
language: node_js
node_js:
- '5'

env:
  matrix:
    - SCRIPT=lint
    - SCRIPT=testOnce
    - SCRIPT=nightwatchCI
  global:
    - CXX=g++-4.8

cache:
  directories:
    - node_modules

before_script:
  - if [ "$SCRIPT" == "nightwatchCI" ]; then npm run startTest & fi
  - if [ "$SCRIPT" == "nightwatchCI" ]; then sleep 15; fi

script: "npm run $SCRIPT"

addons:
  sauce_connect:
    username: "ethcoreHQ"
    access_key: "d8781b6a-0899-4a6e-9138-b808d4d1ded3"