sudo: false
language: node_js
node_js:
  - '5'

matrix:
  include:
  - env: SCRIPT=lint
  - env: SCRIPT=testOnce
  - env: SCRIPT=nightwatchCI
    addons:
      sauce_connect:
        username: "ethcoreHQ"
        access_key:
          secure: "LIDRdFn6xEy4ZZ7RjnWHQoEATJ77GPdTgiFnuYFT9do11ClS+AWgU6V+xEibcdc67YgbASIadOVtouVG8FH04rFb9Nboy8S0Zjqf6b6HQACMXBcPyfPT3lkdIBgLtU9gNb3sgsSLhDMqiRwi52i/gUJRFJaEinyuRmoa+zxLs0k+EkGNYRzxM3P9tiE8oLyVluUiwa2ZUKTEK92C9AaDLrLOS5YfWNuP7+SdmFVEjxOODP7R7CMv4gMbg2U27hpUm1sS9f4uxYxul09E0zr2W27mv3lnf9xS0xJbeceaNly67ir3026B0TOGSm5Dl0QjJpuDyLM1Q77dTFUlpwE/cMpRqtj1z3bZemHbgUS4lCrYwvYS9hRTmrg9qqwxB1/SWCiLzN0+q9fqemQLxPngEV3LFJU5ksymsT7k/tJLByW/2BDL3se2a2JLMFPfGMGOodetnwuAnB61jySGZcFKgyPwVYYwPKgzBgtMnqHMu9TmeRN/0lRcEdNt7TGeBjZqtaLq1bkMTECYHvKxY1L24kk0DI4R0tdgqjJaxdiuwz9fsHMwgL/TIYFLeN1CL8ste4FpDSJLoGrn7oUYr9jsw0qW05gAH12T3ko6t9zZ3RVn7opVn4BvN0HIYisR98A+b+IdHO4Ef6XIAU0RHNhj/oBhF5IGhxdtOBJmG4kJzDk="

cache:
  directories:
    - node_modules

env:
  global:
    - CXX=g++-4.8

before_script:
  - if [ "$SCRIPT" == "nightwatchCI" ]; then npm run startTest & fi
  - if [ "$SCRIPT" == "nightwatchCI" ]; then sleep 15; fi

script: npm run $SCRIPT