sudo: false
language: node_js
node_js:
  - '5'

matrix:
  include:
  - env: SCRIPT=lint
  - env: SCRIPT=testOnce
  - env: SCRIPT=nightwatchCI
    addons:
      sauce_connect:
        username: "ethcoreHQ"
        access_key:
          secure: "DB6edAK3m3C5ZOuj+BXco/NzPJkkBe7CveibSq2JwonuNSZ96L9WY4VFYPTEaM9Unhccc752GhxfczWz5DNxR9Hsp2ZiEYLSrVUm/BlUs8BSbxqpb8KykcFaBibqcXwBsGHbY03N1JEhnll3T76vaIrumq5kEL7uO2IPU0zBLM8/utcWAZlgSxyYFhdTJe5+QFuXy1iYGMiAoDgaUV5StvVLoWBaISI//r26Wu8W5Bmt0WDBx/qu/fh6FkPItzXc997uJ8/0wXx1va2m5V4XXAQ+NusZS8VUGDZ7YUCGm/qNQnaYF7OocZDrBK+f14HhmoFR0QQ14D1McOOW+Ezj+JrgU18+t+Us3q6YjCvZk3eLO3miwbWv+fa/rl17W4GTq5MPZIs/KxVnPjUfzWEef3HbRVDHZuLYqJI4MySTHNTjWoLN3WBtIZPDA+rWWoqhCXjss3zXlbrIlSTQxGCCxLzYnSqiOrH1L/qDdNwQF/+Dn+Y6y8sabmCBBibiMBS4lo/IzDhE54y6e19CfnPSdA7WAbP/2LhYEOxvgKKBv6sqSyGfM6dmX2XgYSP3mx1vhG41e2J3F8irEy0TalDYkzvUdhMQ88APGEAphcsXBS6nRSgXKusAtd1+tslbjcyKfhCtsRf0Td5WiFnbnhfLBo3ZU5WRJunLhjuc++pcsX8="

cache:
  directories:
    - node_modules

env:
  global:
    - CXX=g++-4.8

before_script:
  - if [ "$SCRIPT" == "nightwatchCI" ]; then npm run startTest & fi
  - if [ "$SCRIPT" == "nightwatchCI" ]; then sleep 15; fi

script: npm run $SCRIPT