sudo: false
language: node_js
node_js:
  - '5'

matrix:
  include:
  - env: SCRIPT=lint
  - env: SCRIPT=testOnce
  - env: SCRIPT=nightwatchCI
    addons:
      sauce_connect:
        username: "ethcoreHQ"
        access_key:
          secure: "tJNfOFHhHUaeUNX2FWf0qzY8oblvVxxW6SL5C2rVmhm3qAtPX6xc7JYZTlZAmLG5rjCnF8wVuAoYjZUihVjundBiAP8NZ5+aEr8s0lxo9m8wKaXM9vs2/rNNuuaxLgvd9KZE445d6xeek1lTAsK+A2jji/eGcFOK8MWHpJh8ZrRK7Vjd1vPDrw4MLoA5kAmyYqrzqqDcBrtVdDYyuGIhDZHMQTHB5ry5rkQYhfMsJXqAUD83bGkrH6TpHUv5LlveJapCTCpAy/4vfhLzDZrz7XCwJd7600Ue0q5U6aixe3NGUx+v3jHVCqj9VP/7BI5nYoTTaezylQEAovzF5gnOI+sMZZRUpZexbruAyPz9FkvalOGbgHFb35yL4jpHgTY5Lif+bdR2/wjQmOT+nomVd7FS9HTDNl5sTG8t8o07ygj9HBJmeFL1IEE6iH4npQd2E3P7HGj5XbdX6/xZA0eB9jtxw81geblYW2hTtCpJ6om8Xn/oJJY30Lboza/83hecL+82XKcy7AUIX/jSgenzB0NSVvObGx4fpABEQPq6Ab+KMBTxiCdFoqm4St1YJpvCxYjIbyKaSkE+2yeDyHpZOeUOoQJyAgYD1Gnrrt0dRCvMQm8A1VhcE9IIJPHnCQ4zDywkJyvaEDOo+P93eSUl4ENRwYbBzW1VcuIMjdkRt3E="

cache:
  directories:
    - node_modules

env:
  global:
    - CXX=g++-4.8

before_script:
  - if [ "$SCRIPT" == "nightwatchCI" ]; then npm run startTest & fi
  - if [ "$SCRIPT" == "nightwatchCI" ]; then sleep 15; fi

script: npm run $SCRIPT