language: rust

rust:
  - stable
  - beta
  - nightly
env:
  - PROJECT=home
  - PROJECT=wallet
  - PROJECT=status

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

script:
  - cd $PROJECT
  - cargo build
  - cargo test --release

