sudo: false

branches:
  only:
    - master

language: rust

env:
  global:
    - TRAVIS_NODE_VERSION="6"
    # PARITY WRITE TOKEN
    - secure: "l6dJ0nFhZWLQNelFO92tzHsEt8e9wvQzKBGd5/u8xG4IQz8pcjBpM5e0ZVKm1NUvgExdaOGEvl3kgqVyiMa1HiQQxox3nUCwOaEajEG/7AShoUf9OJuzUGI/pfnp7LmxhF3ZE+d9RSh9CXKkrCOdTpN1PhsijZqfOMolqRToB/puWpCkTW55YuK26q5Ok3YRs00NyZpUMs2uByn00YXuey/1MoLD+boTbcYFyxF+u8lrNv0iYKbx9uvx+ynVRSwd4oy0bt9OBE6mVu14Wa5Ie5/RFFm0JwEhtOq4HkO8d96aHvIK8C2ch63PJciKi2za4RU+VrOxkOt7ib0g1pj91CJMam0rGhetPn5ywL9EUwqt16EXxo0rOTQ9i4zFBoIb01iaXSzdqCGjbXR4VDcjOkS3fLhcEXMguj8K/9KXFLcazs8opohm/ODNPGlJkoh/xrXc80a4fr4o7LNLPxJHEGJcQ90Wvsb0Y/NSIAc//EHOpoHWZRACsmMhI7PfwBdRSWNvWU8re7B8SFb3S2GAAGmOO2oKYzgvLpmY+lQHjVV03ZA47QbCssHkh1/wjWIMT6YFh6a8O7jn8WCQ6t7omkviISzEkERarP7YUw4w70rgOCEwa0JOyjw944N+Yn771Ec/2sf+G+dfXnKi0zeStuUoJYY3E9uz/A2j8o+Bw7o="

matrix:
  include:
    - rust: stable
      env: BUILD=rust
    - rust: stable
      env: BUILD=js

cache:
  cargo: true
  directories:
    - $HOME/.cargo
    - $HOME/.npm
    - $HOME/.nvm
    - $TRAVIS_BUILD_DIR/home/target
    - $TRAVIS_BUILD_DIR/signer/target
    - $TRAVIS_BUILD_DIR/status/target
    - $TRAVIS_BUILD_DIR/wallet/target

install:
  - (test -d ~/.nvm || (
      git clone https://github.com/creationix/nvm.git ~/.nvm &&
      cd ~/.nvm &&
      git checkout `git describe --abbrev=0 --tags`
    )) &&
    source ~/.nvm/nvm.sh &&
    nvm install $TRAVIS_NODE_VERSION
  - ./web.sh install --no-progress --ignore-scripts

script:
  - if [ "$BUILD" = "rust" ]; then ./scripts/build_rs.sh; fi
  - if [ "$BUILD" = "js" ]; then ./scripts/build_js.sh; fi

after_success: |
  [ $TRAVIS_BRANCH = master ] && [ $TRAVIS_PULL_REQUEST = false ] && [ "$BUILD" = "js" ] && \
  ./scripts/deploy.sh
