language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
  env:
    - PROJECT=home
    - PROJECT=wallet

script:
  - cd $PROJECT
  - cargo build
  - cargo test --release
