[package]
description = "Injectable identity manager for Parity"
name = "parity-idmanager"
version = "0.1.2"
license = "GPL-3.0"
authors = ["Ethcore <admin@ethcore.io"]

[dependencies]
parity-webapp = { git = "https://github.com/ethcore/parity-webapp.git" }
