[package]
description = "Mist wallet bundled for parity"
name = "parity-wallet"
version = "0.1.0"
license = "GPL-3.0"
authors = ["Ethcore <admin@ethcore.io"]

[dependencies]
parity-webapp = { path = "../parity-webapp" }
