[package]
description = "Ethereum Wallet Ðapp for Parity"
name = "parity-wallet"
version = "0.4.0"
license = "GPL-3.0"
authors = ["Ethcore <admin@ethcore.io>"]

[dependencies]
parity-webapp = { git = "https://github.com/ethcore/parity-webapp.git", version = "0.2" }
