[package]
description = "Mist wallet bundled for parity"
name = "parity-wallet"
version = "0.2.0"
license = "GPL-3.0"
authors = ["Ethcore <admin@ethcore.io"]

[dependencies]
parity-webapp = { git = "https://github.com/ethcore/parity-webapp.git" }
